### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by sekiranata** [qq-agency/ps.sms#2]
### Модуль

**Версия модуля:** 1.1.1

**Способ установки:** Битрикс Marketplace / Composer

### Битрикс

**Версия Главного модуля:** 18.5.0

**Версия модуля Служба сообщений:** 18.0.0

**Проверка системы:** выдает Не достаточно параметров для выполнения функции

### Проблема

Добрый день
Turbosms
При регистрации по какой-то причине отдает:
Не достаточно параметров для выполнения функции

Подпись зарегистрированы и подтверждена
В админке удалось зайти в шлюз с помощью логина и пароля, вернул точное количество рублей на счете
По примеру из https://turbosms.ua/soap.html удалось отправить тестовую смску через обычный php файл, в чем может быть проблема?

**Comment by sekiranata** [comment]
> ## 🐛 Сообщение об ошибке
> ### Модуль
> **Версия модуля:** 1.1.1
> 
> **Способ установки:** Битрикс Marketplace / Composer
> 
> ### Битрикс
> **Версия Главного модуля:** 18.5.0
> 
> **Версия модуля Служба сообщений:** 18.0.0
> 
> **Проверка системы:** выдает/не выдает ошибки
> 
> ### Проблема
> Добрый день
> Turbosms
> При регистрации по какой-то причине отдает:
> Не достаточно параметров для выполнения функции
> 
> Подпись зарегистрированы и подтверждена
> В админке удалось зайти в шлюз с помощью логина и пароля, вернул точное количество рублей на счете
> По примеру из https://turbosms.ua/soap.html удалось отправить тестовую смску через обычный php файл, в чем может быть проблема?

**Comment by saundefined** [comment]
Для работы с ТурбоСМС необходимо:

1. Указать доступное имя отправителя в настройках модуля `<адрес_сайта>/bitrix/admin/settings.php?lang=ru&mid=ps.sms`
2. В настройках Главного модуля `<адрес_сайта>/bitrix/admin/settings.php?lang=ru&mid=main` на вкладке Почта и СМС выбрать ТурбоСМС и указанное ранее имя отправителя

подскажите, пожалуйста, все ли сейчас так указано?

**Comment by sekiranata** [comment]
Да, выставлены одинаковые настройки на этих вкладках, подключение по шлюзу проходит.
